- hosts: docker
  become: yes
  vars:
    user: lighttpd
    group: lighttpd
  tasks:
  - name: Verificando distribuição
    set_fact:
      user: www-data
      group: www-data
    when: ansible_distribution|lower == 'debian'
  - name: Garantindo o epel-release em CentOS
    package:
      name: epel-release
      state: present
    when: ansible_distribution|lower == 'centos'  
  - name: Garantindo Lighttpd e Git
    package:
      name: ['lighttpd', 'git']
      state: present
  - name: Garantindo configurações
    template:
      src: '{{ item }}'
      dest: /etc/lighttpd
      owner: root
      group: root
    loop: 
    - /root/playbooks/files/lighttpd.conf 
    - /root/playbooks/files/mime-types.conf
    register: config
  - name: Garatindo configurações de proxy
    blockinfile:
      path: /etc/lighttpd/proxy.conf
      create: yes
      block: |
        $SERVER["socket"] == ":8080" {
            proxy.server = ( "" => ( ( "host" => "192.168.10.10", "port" => "80" )))
         }
      insertafter: '# Configurações do Ansible'
    register: proxy
  - name: Garatindo diretórios
    file:
      path: '{{ item }}'
      owner: '{{ user }}'
      group: '{{ group }}'
      state: directory 
    loop:
    - /srv/www/html
    - /var/cache/lighttpd
    - /var/logs/lighttpd 
  - name: Reiniciando Lighttpd para aplicar configurações
    service:
      name: lighttpd
      state: restarted
    when: config.changed or proxy.changed  
  - name: Garantindo serviço do Lighttpd
    service:
      name: lighttpd
      state: started
      enabled: yes
  - name: Removendo arquivos de /srv/www/html
    shell: 'find /srv/www/html/ -delete -mindepth 1'   
  - name: Copiando o site para as máquinas
    unarchive:
      src: /root/arquivo.tar.gz
      dest: /srv/www/html
      extra_opts: '--strip-components=1'
      owner: '{{ user }}'
      group: '{{ group }}'
  - name: Garantindo contexto de /srv/www/html
    command: 'restorecon -R /srv/www/html/'   
    when: ansible_distribution|lower == 'centos'
  - name: Testando conexão com load balancer
    uri:
      url: http://172.27.11.20
      status_code: [200, 201]
    register: response
    delegate_to: localhost
    run_once: yes
#  - name: Verificando status da conexão
#    fail:
#      msg: '[{{ response.status }}] - Load balancer com problemas'
#    when: response.status != 200    
